---
title: 'Lecture 0: Course Introduction'
author: "<br> <br >Yanfei Kang <br> yanfeikang@buaa.edu.cn"
date: "School of Economics and Management <br> Beihang University"
output:
  slidy_presentation:
    footer: "Lecture 0: Course Introduction"
    css: ../styles/ykstyle.css
logo: buaalogo.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General Information

- **Lecturer: ** Yanfei Kang 
- **Language: **The course is taught in Chinese. Materials are in
English.
- **Computer language: R**
- **Reception hours: **Questions concerned with this course can be asked during or after each lecture or via email.
- **Lecture notes: ** available on https://yanfei.site/teaching/dpsa/. Their source codes can be found on  [Github](https://github.com/ykang/Data-Processing-and-Statistical-Analysis).
- **Working load: **Depending on your own situation and you ambition, you decide how much time you want to input. 
- **Course references: ** No specific reference books. References will be given for each lecture.
- **Examinations: **To pass the final exam you have to have to finish a scientific report, the topic of which can be chosen by yourselves. It should be submitted together with source code via email two weeks after the last lecture. You can go with a group with 2 students. Attendence will also be checked and included in your final mark.




# Course contents

- L1: **R** tips
- Collecting and dealing with text data
    + L2: Text processing, web scraping and text mining
- Building models
    + L3: Unsupervised methods
    + L4: Supervised methods
    + L5: Time series forecasting
- L6: Parallel computation with **R**
- Delivering results 
    + L7: Graphics
    + L8: Dynamic Documents



